evolUX.UI/Areas/Finishing/Controllers/PrintController.cs
using evolUX.API.Areas.Core.ViewModels;
using evolUX.UI.Areas.Finishing.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using System.Net;
using System.Data;
using Flurl.Http;
using evolUX.UI.Exceptions;
using Newtonsoft.Json;
using evolUX.UI.Areas.Core.Models;
using Shared.ViewModels.General;
using System.Reflection;
using Shared.Models.Areas.Finishing;
using static Dapper.SqlMapper;
using System.Security.Claims;
using Shared.Models.General;
using Shared.ViewModels.Areas.Core;
using Shared.ViewModels.Areas.Finishing;
using Microsoft.Extensions.Localization;
using Microsoft.IdentityModel.Tokens;

namespace evolUX.UI.Areas.Finishing.Controllers
{
    [Area("Finishing")]
    public class PrintController : Controller
    {
        private readonly IPrintService _printService;
        private readonly IStringLocalizer<PrintController> _localizer;
        public PrintController(IPrintService printService, IStringLocalizer<PrintController> localizer)
        {
            _printService = printService;
            _localizer = localizer;
        }

        public async Task<IActionResult> Printing(string JsonSerializedProductionInfo, string FilePrinterSpecs, 
            string FileName)
        {
            TempData["JsonSerializedProductionInfo"] = JsonSerializedProductionInfo;
            
            ViewBag.FileName = FileName;

            string profileList = HttpContext.Session.GetString("evolUX/Profiles");
            string filesSpecs = FilePrinterSpecs;
            bool ignoreProfiles = false;
            try
            {

                PrinterViewModel result = await _printService.GetPrinters(profileList, filesSpecs, ignoreProfiles);
                result.SetPermissions(HttpContext.Session.GetString("evolUX/Permissions"));
                return View(result);
            }
            catch (ErrorViewModelException ex)
            {
                return View("Error", ex.ViewModel);
            }
            catch (HttpUnauthorizedException ex)
            {
                if (ex.response.Headers.Contains("Token-Expired"))
                {
                    var header = ex.response.Headers.FirstOrDefault("Token-Expired");
                    var returnUrl = Request.Path.Value;
                    //var url = Url.RouteUrl("MyAreas", )

                    return RedirectToAction("Refresh", "Auth", new { Area = "Core", returnUrl = returnUrl });
                }
                else
                {
                    return RedirectToAction("Index", "Auth", new { Area = "Core" });
                }
            }

        }

        public async Task<IActionResult> Print(string Printer, List<string> FileCheck)
        {
            string[] printerValues = Printer.Split('|');
            if (printerValues.Length < 3 || string.IsNullOrEmpty(printerValues[2]))
                return PartialView("MessageView", new MessageViewModel(_localizer["SelectValidPrinter"]));

            if (FileCheck.Count == 0)
            {
                string JsonSerializedProductionInfo = (string)TempData["JsonSerializedProductionInfo"];
                if (JsonSerializedProductionInfo != null)
                {
                    FileCheck.Add(JsonSerializedProductionInfo);
                }
            }

            if (FileCheck.Count == 0)
            {
                return PartialView("MessageView", new MessageViewModel(_localizer["MissingFile"]));
            }

            List<PrintFileInfo> prodFiles = new List<PrintFileInfo>();
            foreach (var prodFile in FileCheck)
            {
                prodFiles.Add(JsonConvert.DeserializeObject<PrintFileInfo>(prodFile));
            }
            
            string ServiceCompanyCode = (string)TempData["ServiceCompanyCode"];
            string username = User.Identity.Name;
            int userid = int.Parse(User.Claims.Where(c => c.Type == ClaimTypes.NameIdentifier)
                                              .Select(c => c.Value)
                                              .SingleOrDefault());
            try
            {
                Result result = await _printService.Print(printerValues[2], ServiceCompanyCode, username, userid, prodFiles);
                return PartialView("MessageView", new MessageViewModel(result.ErrorID.ToString(), "", result.Error));
            }
            catch (ErrorViewModelException ex)
            {
                return PartialView("Error", ex.ViewModel);
            }
            catch (HttpUnauthorizedException ex)
            {
                if (ex.response.Headers.Contains("Token-Expired"))
                {
                    var header = ex.response.Headers.FirstOrDefault("Token-Expired");
                    var returnUrl = Request.Path.Value;
                    //var url = Url.RouteUrl("MyAreas", )

                    return RedirectToAction("Refresh", "Auth", new { Area = "Core", returnUrl = returnUrl });
                }
                else
                {
                    return RedirectToAction("Index", "Auth", new { Area = "Core" });
                }
            }

        }
    }
}

evolUX.UI/Areas/Finishing/Views/Print/Printing.cshtml
@using Shared.Models.Areas.Finishing
@using Shared.ViewModels.Areas.Finishing
@using Newtonsoft.Json;
@using Shared.ViewModels.Areas.Core;

@model PrinterViewModel
@*https://www.w3.org/WAI/tutorials/tables/irregular/  https://datatables.net/extensions/buttons/examples/column_visibility/index.html*@
@{
    bool PrintFile = false;

    if (Model.Permissions.Find(x => x == "PrintFile") != null) { PrintFile = true; }
}
<div class="d-flex justify-content-center" >
    <div class="spinner-border" role="status" id="myLoader" style="display:none">
      <span class="sr-only">Loading...</span>
    </div>
    
</div>

<div class="d-flex justify-content-center">
    <h3 class="display-4 text-center"> Print File</h3>
</div><div class="d-flex justify-content-center">
    <h4 class="display-6 text-center">@ViewBag.FileName</h4>
</div>
<div class="my-5 d-flex justify-content-center">
    <div class=" my-1 d-flex justify-content-center">
        <b class="mx-3">Printer</b>
        <form id="some" asp-area="Finishing" asp-controller="Print" asp-action="Print"
                data-ajax="true"
                data-ajax-method="POST"
                data-ajax-mode="replace"
                data-ajax-update="#response"
                data-ajax-loading="myLoader">

            <select id="Printer" name="Printer">
                @foreach (PrinterInfo printer in Model.Printers.Where(r => r.MatchFilter == true))
                {
                    string resValue = printer.PlexFeature.ToString() + "|" + printer.ColorFeature.ToString() + "|" + printer.ResValue;
                    <option value="@resValue">@printer.Description</option>
                }
            </select>
            <p class="my-3 d-flex justify-content-center"><input type="submit" name="Submit" class="btn btn-block btn-primary" /></p>

        </form>
        <form id="all" style="display:none" asp-area="Finishing" asp-controller="Print" asp-action="Print"
                data-ajax="true"
                data-ajax-method="POST"
                data-ajax-mode="replace"
                data-ajax-update="#response"
                data-ajax-loading="myLoader">

                <select id="Printer" name="Printer">
                @foreach(PrinterInfo printer in Model.Printers)
                {
                    string resValue = printer.PlexFeature.ToString() + "|" + printer.ColorFeature.ToString() + "|" + printer.ResValue;
                    <option value="@resValue">@printer.Description</option>
                }
                </select>
            <p class="my-3 d-flex justify-content-center"><input type="submit" name="Submit" class="btn btn-block btn-success" /></p>

        </form>
    </div>
    <div class="checkbox mx-3 my-1">
        <label> @Html.CheckBox("check", false) All Printers</label>
    </div>
    
    @*<div class ="d-flex justify-content-center">
        <button type="button" class="btn btn-primary" id="submit">Submit Print</button>
    </div>*@
    <div id="response" class="d-flex justify-content-center">
        
    </div>
</div>
@section Scripts
{
    <script type="text/javascript">
        $(function () {
            $("#check").click(function () {
                if ($(this).is(':checked')) {
                    $("#all").show();
                    $("#some").hide();
                } else {
                    $("#all").hide();
                    $("#some").show();
                }
            });
        });
    </script>
    <script type="text/javascript">
        $(function () {
            $("#submit").click(function () {
                if ($('#check').is(':checked')) {
                    document.getElementById("all").submit();
                } else {
                    document.getElementById("some").submit();
                }
            });
        });
    </script>
}